"""Foresight AI - Attack Forecasting & Model Management ORM Models."""

import uuid
from datetime import datetime
from sqlalchemy import DateTime, Float, Index, Integer, JSON, String
from sqlalchemy.orm import Mapped, mapped_column
from app.db.base import Base, TimestampMixin


class ForecastWindow(Base, TimestampMixin):
    """Represents a time-bounded aggregation window used for temporal feature extraction."""
    __tablename__ = "forecast_windows"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        index=True
    )
    window_start: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True, nullable=False)
    window_end: Mapped[datetime] = mapped_column(DateTime(timezone=True), index=True, nullable=False)
    window_duration_seconds: Mapped[int] = mapped_column(Integer, nullable=False)
    target_entity: Mapped[str] = mapped_column(String(100), default="NETWORK_GLOBAL", index=True, nullable=False)
    flow_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    aggregated_features: Mapped[dict] = mapped_column(JSON, default=dict, nullable=False)


class AttackForecast(Base, TimestampMixin):
    """First-class entity storing temporal attack forecasts generated by Foresight AI."""
    __tablename__ = "attack_forecasts"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        index=True
    )
    window_id: Mapped[str] = mapped_column(String(64), index=True, nullable=True)
    forecast_timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        index=True,
        nullable=False
    )
    target_timestamp: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        index=True,
        nullable=False
    )
    horizon_minutes: Mapped[int] = mapped_column(Integer, index=True, nullable=False)
    predicted_threat: Mapped[str] = mapped_column(String(100), index=True, nullable=False)
    probability: Mapped[float] = mapped_column(Float, nullable=False)
    raw_probability: Mapped[float] = mapped_column(Float, nullable=True)
    decision_threshold: Mapped[float] = mapped_column(Float, default=0.50, nullable=False)
    binary_alert_decision: Mapped[bool] = mapped_column(default=False, index=True, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    anomaly_score: Mapped[float] = mapped_column(Float, nullable=False)
    risk_level: Mapped[str] = mapped_column(String(32), index=True, nullable=False)  # LOW, MEDIUM, HIGH, CRITICAL
    
    # Uncertainty quantification and Conformal sets
    conformal_prediction_set: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    uncertainty_metrics: Mapped[dict] = mapped_column(JSON, default=dict, nullable=False)
    
    # Model attribution & Explainability
    model_version: Mapped[str] = mapped_column(String(50), nullable=False)
    calibration_version: Mapped[str] = mapped_column(String(50), default="v1.0.0-isotonic", nullable=False)
    feature_contributions: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    target_asset: Mapped[str] = mapped_column(String(100), default="GLOBAL_PERIMETER", nullable=False)
    
    # Ground truth validation link (for retrospective calibration tracking)
    actual_outcome: Mapped[str] = mapped_column(String(100), nullable=True)
    is_verified: Mapped[bool] = mapped_column(default=False, nullable=False)

    __table_args__ = (
        Index("idx_forecast_time_threat", "forecast_timestamp", "predicted_threat"),
        Index("idx_forecast_risk_horizon", "risk_level", "horizon_minutes"),
        Index("idx_forecast_alert_time", "binary_alert_decision", "forecast_timestamp"),
    )



class ModelVersion(Base, TimestampMixin):
    """Registry of trained forecasting models, calibration parameters, and performance metrics."""
    __tablename__ = "model_versions"

    id: Mapped[str] = mapped_column(
        String(36),
        primary_key=True,
        default=lambda: str(uuid.uuid4()),
        index=True
    )
    version_tag: Mapped[str] = mapped_column(String(50), unique=True, index=True, nullable=False)
    model_architecture: Mapped[str] = mapped_column(String(100), nullable=False)
    status: Mapped[str] = mapped_column(String(32), default="ACTIVE", nullable=False)  # ACTIVE, CANDIDATE, RETIRED
    brier_score: Mapped[float] = mapped_column(Float, nullable=True)
    expected_calibration_error: Mapped[float] = mapped_column(Float, nullable=True)
    f1_score: Mapped[float] = mapped_column(Float, nullable=True)
    hyperparameters: Mapped[dict] = mapped_column(JSON, default=dict, nullable=False)
    description: Mapped[str] = mapped_column(String(500), nullable=True)
